#!/usr/bin/env bash

# Prints help text
help()
{
  cat <<EOF

  USAGE:

EOF
}

color()
{
printf '\033[%sm%s\033[m' "$@"
# usage:
# color "31;5" "string"
# 0 default
# 5 blink, 1 strong, 4 underlined
# fg: 31 red,  32 green, 33 yellow, 34 blue, 35 purple, 36 cyan, 37 white
# bg: 40 black, 41 red, 44 blue, 45 purple
}

horse()
{
  echo "
                                                    \`T\",.\`-, 
                                                       '8, :. 
                                                \`\"\"\`oooob.\"T,. 
                                              ,-\`\".)O;8:doob.'-. 
                                       ,..\`'.'' -dP()d8O8Yo8:,..\`, 
                                     -o8b-     ,..)doOO8:':o; \`Y8.\`, 
                                    ,..bo.,.....)OOO888o' :oO.  \".  \`-. 
                                  , \"\`\"d....88OOOOO8O88o  :O8o;.    ;;,b 
                                 ,dOOOOO\"\"\"\"\"\"\"\"O88888o:  :O88Oo.;:o888d 
                                 \"\"888Ob...,-- :o88O88o:. :o'\"\"\"\"\"\"\"Y8OP 
                                 d8888.....,.. :o8OO888:: :: 
                                \"\" .dOO8bo\`'',,;O88O:O8o: ::, 
                                   ,dd8\".  ,-)do8O8o:\"\"\"; ::: 
                                   ,db(.  T)8P:8o:::::    ::: 
                                   -\"\",\`(;O\"KdOo::        ::: 
                                     ,K,'\".doo:::'        :o: 
                                      .doo:::\"\"\"::  :.    'o: 
          ,..            .;ooooooo..o:\"\"\"\"\"     ::;. ::;.  'o. 
     ,, \"'    \` ..   .d;o:\"\"\"'                  ::o:;::o::  :; 
     d,         , ..ooo::;                      ::oo:;::o\"'.:o 
    ,d'.       :OOOOO8Oo::\" '.. .               ::o8Ooo:;  ;o: 
    'P\"   ;  ;.OPd8888O8::;. 'oOoo:.;..         ;:O88Ooo:' O\"' 
    ,8:   o::oO\` 88888OOo:::  o8O8Oo:::;;     ,;:oO88OOo;  ' 
   ,YP  ,::;:O:  888888o::::  :8888Ooo::::::::::oo888888o;. , 
   ',d: :;;O;:   :888888::o;  :8888888Ooooooooooo88888888Oo; , 
   dPY:  :o8O     YO8888O:O:;  O8888888888OOOO888\"\" Y8o:O88o; , 
  ,' O:  'ob\`      \"8888888Oo;;o8888888888888'\"'     \`8OO:.\`OOb . 
  '  Y:  ,:o:       \`8O88888OOoo\"\"\"\"\"\"\"\"\"\"\"'           \`OOob\`Y8b\` 
     ::  ';o:        \`8O88o:oOoP                        \`8Oo \`YO. 
     \`:   Oo:         \`888O::oP                          88O  :OY 
      :o; 8oP         :888o::P                           do:  8O: 
     ,ooO:8O'       ,d8888o:O'                          dOo   ;:. 
     ;O8odo'        88888O:o'                          do::  oo.: 
    d\"\`)8O'         \"YO88Oo'                          \"8O:   o8b' 
   ''-'\`\"            d:O8oK                          dOOo'  :o\": 
                     O:8o:b.                        :88o:   \`8:, 
                     \`8O:;7b,.                       \`\"8'     Y: 
                      \`YO;\`8b' 
                       \`Oo; 8:. 
                        \`OP\"8.\` 
                         :  Y8P 
                         \`o  \`, 
                          Y8bod. 
                          \`\"\"\"\"' 
  "

}

ipa()
{
  # parse $PATH into list
  PATHS=$(echo $PATH | tr ':' '\n')

  # counter
  n=1

  for p in $PATHS
  do

    # check if path exists
    if [ -d "$p" ]; then
      color '32;1' "[$n]  "
    else
      color '31;1' "[$n]  "
    fi

    # print path
    echo "$p "

    # increment
    (( n = n + 1 ))

  done

}

# show help for no arguments if stdin is a terminal
if [ "$1" == '-h' ]
then
	help
	exit
fi

# runner
ipa
