#!/usr/bin/env bash

# Prints help text
help()
{
  cat <<EOF

  USAGE:

EOF
}

ipa()
{

  PATHS=$(echo $PATH | tr ':' '\n')

  for p in $PATHS
  do
    echo $p

    if [ -d "$p" ]; then
        echo 'path exists'
    fi

  done

}


# show help for no arguments if stdin is a terminal
if [ "$1" == '-h' ]
then
	help
	exit
fi


ipa
