#!/usr/bin/env bash

# Prints help text
help()
{
  cat <<EOF

  USAGE:

EOF
}

ipa()
{

  # parse $PATH into list
  PATHS=$(echo $PATH | tr ':' '\n')

  for p in $PATHS
  do

    # check if path entry exists
    if [ -d "$p" ]; then
      echo 'path exists'
    fi

    # print path
    echo $p

  done

}

# show help for no arguments if stdin is a terminal
if [ "$1" == '-h' ]
then
	help
	exit
fi

# runner
ipa
